# 数据库配置
spring.datasource:
    url: jdbc:mysql://localhost:3306/garden_cfg?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis.config= classpath:mybatis-config.xml
mybatis.mapperLocations: classpath:org/garden/cfg/core/repository/mapper/*.xml

spring:
  mvc:
    view:
      suffix: .html
      prefix: /public