# 数据库配置
spring.datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

# mybatis.config= classpath:mybatis-config.xml
# mybatis.mapperLocations: classpath:mappers/*.xml

spring:
  mvc:
    view:
      suffix: .html
      prefix: /